slug: training-suraksha-saathis
title: Training of Suraksha Saathis for Anand, Bharuch & Vadodara
date: 04–06 November, 2025
venue: Vadodara
summary: >-
  A three-day training for 30 volunteers from 11 NGOs across Jambusar, Savli, Padra and Ankleshwar on First Aid, Search
  & Rescue, the DRM Cycle, industrial risk management and animal sensitisation.
details:
  - >-
    Anand, Bharuch and Vadodara are prone to flash floods and are at risk of industrial disasters because these
    districts are saturated with industries. In the Inter Agency Group (IAG), Gujarat meeting of Nov 2024 it was
    discussed that a 3-day Suraksha Saathi Training needs to be conducted for the Vadodara Cluster.
  - >-
    This need emerged because during the monsoons because of extreme inundation in the aforementioned urban areas often
    a need emerges for immediate Search, Rescue and response. A training program was held for local volunteers to orient
    them as Suraksha Saathis. They were identified and mobilized by IAG Members from the aforementioned districts.
  - >-
    A Suraksha Saathi is a trained community volunteer who has been already serving as a local development worker. They
    are equipped with the necessary skills to identify risks, carry out rescue operations, and provide immediate
    assistance to affected individuals and families during emergencies.
  - >-
    A 3-day workshop was organized in Vadodara to train the local volunteers on First Aid, Search & Rescue (SAR), DRM
    Cycle, Fundamentals of Industrial Risk Management & Identification, and sensitization and management of animals. The
    training program was from 4 – 6 November, 2025.
  - >-
    A total of 30 volunteers (13 female and 17 male) from 11 NGOs across Jambusar, Savli, Padra, and Ankleshwar
    participated in the training program.
  - >-
    Suresh Gami, from Gujaid explained about the technical aspects of Life-Saving Techniques, Rescue and Emergency First
    Aid. Vidyala Ravi oriented about understanding industrial disaster risks & role of community volunteers. Ms. Khyati
    Panchal took a session on Identification, sensitization and management of animals in Vadodara. Ms. Shailesh Rathod &
    Kirit Parmar took sessions on Different Disasters and Their Impact, Role of Different Stakeholders – Pre, During,
    and Post Disaster, Importance of Personal, Household, Community Emergency Response – Preparedness for Response and
    Damage Assessment & Compensation.
images:
  - /images/updates/training-suraksha-saathis/ss-website-1.jpg
  - /images/updates/training-suraksha-saathis/ss-website-2.jpg
  - /images/updates/training-suraksha-saathis/ss-website-3.jpg
  - /images/updates/training-suraksha-saathis/ss-website-4.jpg
  - /images/updates/training-suraksha-saathis/ss-website-5.jpg
  - /images/updates/training-suraksha-saathis/ss-website-6.jpg
  - /images/updates/training-suraksha-saathis/ss-website-7.jpg
order: 8
